name: Simple manual workflow - Three Env

on:
  pull_request:
    branches:
      -main

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: 
          echo "I am running a job in the DEV Env"

  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: 
          echo "I am running a job in the QA Env"

  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: QA
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: 
          echo "I am running a job in the PROD Env"
